In [1]:
import numpy as np 
import pandas as pd 
data = pd.read_csv("books.csv")
data.head() #prints first 5 rows of dataset

   id                   title               author    year
0   1  In Search of Lost Time        Marcel Proust  1913.0
1   2             Don Quixote  Miguel de Cervantes  1605.0
2   3                 Ulysses          James Joyce  1922.0
3   4        The Great Gatsby  F. Scott Fitzgerald  1925.0
4   5               Moby Dick      Herman Melville  1851.0

In [2]:
data.tail(10) #prints last 10 rows of dataset

,id,title,author,year
2083,2082,Gormenghast,Mervyn Peake,1950.0
2084,2083,The Chronicles of Narnia,C. S. Lewis,1950.0
2085,2084,The Works of Moliere,Moli̬re,1673.0
2086,2085,The Deptford Trilogy,Robertson Davies,1970.0
2087,2086,The Human Comedy,Honor̩ de Balzac,1845.0
2088,2087,The Complete Plays of Jean Racine,Jean Racine,1699.0
2089,2088,Your Face Tomorrow: Dance and dream,Javier Mar�_as,2004.0
2090,2089,Your Face Tomorrow: Fever and Spear,Javier Mar�_as,2002.0
2091,2090,"Your Face Tomorrow: Poison, Shadow and Farewell",Javier Marias,2007.0
2092,2091,The Forsyte Saga,John Galsworthy,1922.0

In [3]:
data.columns #gives names of columns

Index([u'id', u'title', u'author', u'year'], dtype='object')

In [4]:
data.describe() #gives basic statistics of dataset

                id         year
count  2093.000000  2047.000000
mean   1045.164357  1886.564240
std     604.080664   344.415228
min       1.000000  -700.000000
25%     522.000000  1923.000000
50%    1045.000000  1962.000000
75%    1568.000000  1990.000000
max    2091.000000  2018.000000

In [5]:
data.T #transponds data

,0,1,2,3,4,5,6,7,8,9,...,2083,2084,2085,2086,2087,2088,2089,2090,2091,2092
id,1,2,3,4,5,6,7,8,9,10,...,2082,2083,2084,2085,2086,2087,2088,2089,2090,2091
title,In Search of Lost Time,Don Quixote,Ulysses,The Great Gatsby,Moby Dick,Hamlet,War and Peace,The Odyssey,One Hundred Years of Solitude,The Divine Comedy,...,Gormenghast,The Chronicles of Narnia,The Works of Moliere,The Deptford Trilogy,The Human Comedy,The Complete Plays of Jean Racine,Your Face Tomorrow: Dance and dream,Your Face Tomorrow: Fever and Spear,"Your Face Tomorrow: Poison, Shadow and Farewell",The Forsyte Saga
author,Marcel Proust,Miguel de Cervantes,James Joyce,F. Scott Fitzgerald,Herman Melville,William Shakespeare,Leo Tolstoy,Homer,Gabriel Garcia Marquez,Dante Alighieri,...,Mervyn Peake,C. S. Lewis,Moli̬re,Robertson Davies,Honor̩ de Balzac,Jean Racine,Javier Mar�_as,Javier Mar�_as,Javier Marias,John Galsworthy
year,1913,1605,1922,1925,1851,1601,1869,-700,1967,1472,...,1950,1950,1673,1970,1845,1699,2004,2002,2007,1922

In [6]:
sample_data = data.sample(20) #took sample data for easier analysis 
sample_data

,id,title,author,year
106,107,The Color Purple,Alice Walker,1982.0
604,603,World of Wonders,Robertson Davies,1975.0
324,323,Kim,Rudyard Kipling,1901.0
590,589,Los lanzallamas,Roberto Arlt,1931.0
1961,1960,Easy Travel to Other Planets,Ted Mooney,1981.0
1577,1576,The Waters of Kronos,Conrad Richter,1960.0
222,221,Rabbit Redux,John Updike,1971.0
2063,2062,Outside Over There,Maurice Sendak,1981.0
826,825,Smoky the Cowhorse,Will James,1927.0
1310,1309,Spoon River Anthology,Edgar Lee Masters,1915.0
628,627,The Time of the Hero,Mario Vargas Llosa,1963.0
2006,2005,How Far Can You Go?,David Lodge,1980.0
1751,1750,Pushcart Prize Anthology,Pushcart Prize,1976.0
257,256,The Big Sleep,Raymond Chandler,1939.0
1170,1169,"Percy Jackson and the Olympians, Book One: Lig...",Rick Riordan,NaN
832,831,Forever: A Novel,Pete Hamill,2003.0
877,876,Italian Folktales,Italo Calvino,1956.0
1702,1701,The Mask of Dimitrios,Eric Ambler,1944.0
169,169,Doctor Zhivago,Boris Pasternak,1957.0
924,923,The House of the Seven Gables,Nathaniel Hawthorne,1851.0

In [7]:
sample_data.sort_index(axis = 0) #sorts by row

,id,title,author,year
106,107,The Color Purple,Alice Walker,1982.0
169,169,Doctor Zhivago,Boris Pasternak,1957.0
222,221,Rabbit Redux,John Updike,1971.0
257,256,The Big Sleep,Raymond Chandler,1939.0
324,323,Kim,Rudyard Kipling,1901.0
590,589,Los lanzallamas,Roberto Arlt,1931.0
604,603,World of Wonders,Robertson Davies,1975.0
628,627,The Time of the Hero,Mario Vargas Llosa,1963.0
826,825,Smoky the Cowhorse,Will James,1927.0
832,831,Forever: A Novel,Pete Hamill,2003.0
877,876,Italian Folktales,Italo Calvino,1956.0
924,923,The House of the Seven Gables,Nathaniel Hawthorne,1851.0
1170,1169,"Percy Jackson and the Olympians, Book One: Lig...",Rick Riordan,NaN
1310,1309,Spoon River Anthology,Edgar Lee Masters,1915.0
1577,1576,The Waters of Kronos,Conrad Richter,1960.0
1702,1701,The Mask of Dimitrios,Eric Ambler,1944.0
1751,1750,Pushcart Prize Anthology,Pushcart Prize,1976.0
1961,1960,Easy Travel to Other Planets,Ted Mooney,1981.0
2006,2005,How Far Can You Go?,David Lodge,1980.0
2063,2062,Outside Over There,Maurice Sendak,1981.0

In [8]:
sample_data.sort_index(axis = 1)#sorts by column name

,author,id,title,year
106,Alice Walker,107,The Color Purple,1982.0
604,Robertson Davies,603,World of Wonders,1975.0
324,Rudyard Kipling,323,Kim,1901.0
590,Roberto Arlt,589,Los lanzallamas,1931.0
1961,Ted Mooney,1960,Easy Travel to Other Planets,1981.0
1577,Conrad Richter,1576,The Waters of Kronos,1960.0
222,John Updike,221,Rabbit Redux,1971.0
2063,Maurice Sendak,2062,Outside Over There,1981.0
826,Will James,825,Smoky the Cowhorse,1927.0
1310,Edgar Lee Masters,1309,Spoon River Anthology,1915.0
628,Mario Vargas Llosa,627,The Time of the Hero,1963.0
2006,David Lodge,2005,How Far Can You Go?,1980.0
1751,Pushcart Prize,1750,Pushcart Prize Anthology,1976.0
257,Raymond Chandler,256,The Big Sleep,1939.0
1170,Rick Riordan,1169,"Percy Jackson and the Olympians, Book One: Lig...",NaN
832,Pete Hamill,831,Forever: A Novel,2003.0
877,Italo Calvino,876,Italian Folktales,1956.0
1702,Eric Ambler,1701,The Mask of Dimitrios,1944.0
169,Boris Pasternak,169,Doctor Zhivago,1957.0
924,Nathaniel Hawthorne,923,The House of the Seven Gables,1851.0

In [9]:
data[150:200]#specify id to analyze

,id,title,author,year
150,150,Women in Love,D. H. Lawrence,1920.0
151,151,A Confederacy of Dunces,John Kennedy Toole,1980.0
152,152,White Teeth,Zadie Smith,2000.0
153,153,Collected Poems,Wallace Stevens,1955.0
154,154,American Pastoral,Philip Roth,1997.0
155,155,The Poems of Robert Frost,Robert Frost,1969.0
156,156,Epic of Gilgamesh,Unknown,-600.0
157,157,Ph̬dre,Jean Racine,1677.0
158,158,The Stories of John Cheever,John Cheever,1978.0
159,159,Lost Illusions,Honor̩ de Balzac,1837.0
160,160,The Complete Sherlock Holmes,Arthur Conan Doyle,1887.0
161,161,The Suppliants,Aeschylus,-470.0
162,162,Seven Against Thebes,Aeschylus,-467.0
163,163,The Persians,Aeschylus,-472.0
164,164,The Corrections,Jonathan Franzen,2001.0
165,165,An American Tragedy,Theodore Dreiser,1925.0
166,166,A Room With a View,E.M. Forster,1908.0
167,167,Tartuffe,Moli̬re,1664.0
168,168,The Ambassadors,Henry James,1903.0
169,169,Doctor Zhivago,Boris Pasternak,1957.0
170,170,Confessions of Zeno,Italo Svevo,1923.0
171,171,Jude the Obscure,Thomas Hardy,1895.0
172,172,Henderson The Rain King,Saul Bellow,1959.0
173,173,The Stand,Stephen King,1978.0
174,174,A Tale of Two Cities,Charles Dickens,1859.0
175,175,Eugenie Grandet,Honor̩ de Balzac,1833.0
176,176,Philoctetes,Sophocles,-409.0
177,177,Ajax,Sophocles,-450.0
178,178,Women of Trachis,Sophocles,-410.0
179,179,Rabbit Is Rich,John Updike,1981.0
180,180,"The Lion, The Witch and the Wardrobe",C.S. Lewis,1950.0
181,181,Of Mice and Men,John Steinbeck,1937.0
182,182,The Plague,Albert Camus,1947.0
183,183,Wide Sargasso Sea,Jean Rhys,1966.0
184,184,The Leopard,Giuseppe Tomasi di Lampedusa,1958.0
185,185,The Remains of the Day,Kazuo Ishiguro,1989.0
186,186,2666,Roberto Bolano,2004.0
187,187,Tender Is the Night,F. Scott Fitzgerald,1934.0
188,188,Rabbit at Rest,John Updike,1990.0
189,189,The Man Without Qualities,Robert Musil,1930.0
190,190,Persuasion,Jane Austen,1818.0
191,191,The Strange Case of Dr. Jekyll and Mr. Hyde,Robert Louis Stevenson,1886.0
192,192,Light in August,William Faulkner,1932.0
193,193,Clarissa,Samuel Richardson,1748.0
194,194,A Tree Grows in Brooklyn,Betty Smith,1943.0
195,195,U.S.A. Trilogy,John Dos Passos,1938.0
196,195,The Picture of Dorian Gray,Oscar Wilde,1890.0
197,196,Dubliners,James Joyce,1914.0
198,197,Household Tales,Brothers Grimm,1812.0
199,198,Pedro Paramo,Juan Rulfo,1955.0

In [10]:
data.iloc[3:5]

   id             title               author    year
3   4  The Great Gatsby  F. Scott Fitzgerald  1925.0
4   5         Moby Dick      Herman Melville  1851.0

In [11]:
data[data['year'] > 1980] #gives data if boolean condition is met

,id,title,author,year
40,41,Beloved,Toni Morrison,1987.0
53,54,Midnight's Children,Salman Rushdie,1981.0
104,105,Stories of Ernest Hemingway,Ernest Hemingway,1987.0
106,107,The Color Purple,Alice Walker,1982.0
136,137,Atonement,Ian McEwan,2002.0
138,139,The Handmaid's Tale,Margaret Atwood,1985.0
142,143,Blood Meridian,Cormac McCarthy,1986.0
152,152,White Teeth,Zadie Smith,2000.0
154,154,American Pastoral,Philip Roth,1997.0
164,164,The Corrections,Jonathan Franzen,2001.0
179,179,Rabbit Is Rich,John Updike,1981.0
185,185,The Remains of the Day,Kazuo Ishiguro,1989.0
186,186,2666,Roberto Bolano,2004.0
188,188,Rabbit at Rest,John Updike,1990.0
200,199,A Prayer for Owen Meany,John Irving,1989.0
201,200,Harry Potter And The Philosopher's Stone,J. K. Rowling,1997.0
203,202,The Brief Wondrous Life of Oscar Wao,Junot Diaz,2007.0
205,204,Never Let Me Go,Kazuo Ishiguro,2005.0
220,219,Austerlitz,W. G. Sebald,2001.0
227,226,The Amazing Adventures of Kavalier and Clay,Michael Chabon,2000.0
230,229,Middlesex,Jeffrey Eugenides,2002.0
238,237,The Wind-Up Bird Chronicle,Haruki Murakami,1994.0
243,242,Possession,A.S. Byatt,1990.0
245,244,Love in the Time of Cholera,Gabriel Garcia Marquez,1985.0
250,249,The Road,Cormac McCarthy,2006.0
253,252,The House of the Spirits,Isabel Allende,1982.0
256,255,The Book of Disquiet,Fernando Pessoa,1982.0
261,260,Wolf Hall,Hilary Mantel,2009.0
262,261,Selected Stories of Alice Munro,Alice Munro,1996.0
271,270,The Unbearable Lightness of Being,Milan Kundera,1984.0
...,...,...,...,...
2036,2035,A Perfect Spy,John le Carr̩,1986.0
2039,2038,Day,A.L. Kennedy,2007.0
2040,2039,The Beginning of Spring,Penelope Fitzgerald,1988.0
2042,2041,My Name Is Lucy Barton,Elizabeth Strout,2016.0
2044,2043,The Time Traveler's Wife,Audrey Niffenegger,2003.0
2047,2046,CivilWarLand in Bad Decline,George Saunders,1996.0
2048,2047,Poor Things,Alasdair Gray,1992.0
2049,2048,Kruger's Alp,Christopher Hope,1984.0
2050,2049,Dangerous Laughter,Steven Millhauser,2008.0
2051,2050,The Queen of the Tambourine,Jane Gardam,1991.0
2052,2051,On the Bus with Rosa Parks,Rita Dove,1999.0
2054,2053,Samuel Pepys: The Unequalled Self,Claire Tomalin,2002.0
2057,2056,Fools of Fortune,William Trevor,1983.0
2059,2058,City of Glass,Paul Auster,1985.0
2062,2061,Theory of War,Joan Brady,1993.0
2063,2062,Outside Over There,Maurice Sendak,1981.0
2064,2063,Spies,Michael Frayn,2002.0
2065,2064,The Comforts of Madness,Paul Sayer,1988.0
2066,2065,Felicia's Journey,William Trevor,1994.0
2067,2066,Landing Light,Don Paterson,2003.0
2068,2067,The Hand That First Held Mine,Maggie O'Farrell,2010.0
2069,2068,Silver City,Maurice Leitch,1981.0
2072,2071,Geek Love: A Novel,Katherine Dunn,1989.0
2073,2072,The Tenderness of Wolves,Stef Penney,2006.0
2074,2073,Bad Behavior: Stories,Mary Gaitskill,1988.0
2075,2074,Extremely Loud and Incredibly Close,Jonathan Safran Foer,2005.0
2076,2075,The Epicure's Lament,Kate Christensen,2004.0
2089,2088,Your Face Tomorrow: Dance and dream,Javier Mar�_as,2004.0
2090,2089,Your Face Tomorrow: Fever and Spear,Javier Mar�_as,2002.0
2091,2090,"Your Face Tomorrow: Poison, Shadow and Farewell",Javier Marias,2007.0

In [12]:
data.groupby('year').sum()#adds id based on specific year

            id
year
-700.0    2651
-600.0    1528
-570.0    1232
-560.0     487
-475.0     456
-472.0     163
-470.0     161
-467.0     162
-458.0      77
-450.0     177
-442.0      59
-438.0     777
-431.0     141
-429.0      48
-428.0     401
-423.0     294
-415.0     496
-414.0     263
-411.0     227
-410.0     178
-409.0     309
-405.0     254
-401.0      94
-316.0    1600
-300.0    1380
-200.0     296
-55.0      250
-23.0      409
-19.0       39
 8.0      1440
...        ...
 1989.0  23762
 1990.0  34763
 1991.0  25828
 1992.0  30978
 1993.0  20340
 1994.0  25049
 1995.0  31257
 1996.0  21574
 1997.0  19114
 1998.0  22530
 1999.0  30340
 2000.0  17533
 2001.0  25736
 2002.0  34419
 2003.0  30155
 2004.0  29366
 2005.0  33148
 2006.0  37290
 2007.0  24155
 2008.0  25260
 2009.0  24854
 2010.0  15898
 2011.0  21163
 2012.0  14744
 2013.0  11821
 2014.0  12842
 2015.0   6457
 2016.0   8169
 2017.0  11470
 2018.0   2777

[334 rows x 1 columns]

In [13]:
sample_data.stack()

106   id                                                      107
      title                                      The Color Purple
      author                                         Alice Walker
      year                                                   1982
604   id                                                      603
      title                                      World of Wonders
      author                                     Robertson Davies
      year                                                   1975
324   id                                                      323
      title                                                   Kim
      author                                      Rudyard Kipling
      year                                                   1901
590   id                                                      589
      title                                       Los lanzallamas
      author                                         Roberto Arlt
      year                                                   1931
1961  id                                                     1960
      title                          Easy Travel to Other Planets
      author                                           Ted Mooney
      year                                                   1981
1577  id                                                     1576
      title                                  The Waters of Kronos
      author                                       Conrad Richter
      year                                                   1960
222   id                                                      221
      title                                          Rabbit Redux
      author                                          John Updike
      year                                                   1971
2063  id                                                     2062
      title                                    Outside Over There
                                      ...
1751  title                              Pushcart Prize Anthology
      author                                       Pushcart Prize
      year                                                   1976
257   id                                                      256
      title                                         The Big Sleep
      author                                     Raymond Chandler
      year                                                   1939
1170  id                                                     1169
      title     Percy Jackson and the Olympians, Book One: Lig...
      author                                         Rick Riordan
832   id                                                      831
      title                                      Forever: A Novel
      author                                          Pete Hamill
      year                                                   2003
877   id                                                      876
      title                                     Italian Folktales
      author                                        Italo Calvino
      year                                                   1956
1702  id                                                     1701
      title                                 The Mask of Dimitrios
      author                                          Eric Ambler
      year                                                   1944
169   id                                                      169
      title                                        Doctor Zhivago
      author                                      Boris Pasternak
      year                                                   1957
924   id                                                      923
      title                         The House of the Seven Gables
      author                                  Nathaniel Hawthorne
      year                                                   1851
Length: 79, dtype: object